ORCID_APPID: 'ORCID_APPID'
ORCID_REDIRECT_URI: 'ORCID_REDIRECT_URI'
ORCID_SECRET: 'ORCID_SECRET'
ORCID_TOKEN_REDIRECT_URI: 'ORCID_TOKEN_REDIRECT_URI'
AWS_ACCESS_KEY_ID: 'AWS_ACCESS_KEY_ID'
AWS_SECRET_ACCESS_KEY: 'AWS_SECRET_ACCESS_KEY'
ZENODO_CLIENT_ID: 'ZENODO_CLIENT_ID'
ZENODO_CLIENT_SECRET: 'ZENODO_CLIENT_SECRET'
ZENODO_ACCESS_TOKEN: 'ZENODO_ACCESS_TOKEN'
ELASTIC_SEARCH_URL: 'ELASTIC_SEARCH_URL'
ELASTIC_SEARCH_INDEX: 'ELASTIC_SEARCH_INDEX'
ELASTIC_SEARCH_AUTH: 'ELASTIC_SEARCH_AUTH'
HOSTNAME: 'localhost'
REDISURL: 'redis://localhost:6379/0'
CELERYAPP: 'recastfrontend.celeryapp'
FLASKCONFIG: 'recastfrontend.flaskconfig'
DATA_FOLDER: 'data/'
DBPATH: 'sqlite:///tmp.db'